### ISSUE TITLE
RTL markdown

### ISSUE THREAD

**Issue by mhemrg** [pr-techblog/pr-techblog#34]
LTR direction in markdown files is annoying. How do you deal with it?

**Comment by farskid** [comment]
در مورد کدوم فایل های مارک داون صحبت میکنین؟

**Comment by mhemrg** [comment]
من اگه بخوام یه نوشته رو توی این وبلاگ منتشر کنم، مگه نباید متن‌ام رو توی یه فایل مارک‌داون بنویسم؟

**Comment by farskid** [comment]
بله باید همینکار رو کنین. البته چندن مرحله قبلش شامل فورک کردن ریپو و اضافه کردن اطلاعات شخصی تون هم هست.
ازین بابت توی ریدمی ریپو کمی اطلاعات کم هست و به زودی مراحل کاملش رو مینویسیم.
اما برای نوشتن توی فایل مارک داون من ادیتور
VSCODE
رو پیشنهاد میکنم. برای تلفیق کلمات فارسی و غیر فارسی هم خوب عمل میکنه.

**Comment by mhemrg** [comment]
دقیقا من هم دنبال ابزار هستم. ابزاری که بشه باهاش راحت‌تر با این مشکل چپ‌چین بودن کنار اومد.
این ابزار هم به نظرم کاربردی هست: http://dariubs.github.io/rtlmd/

**Comment by farskid** [comment]
این هم خوبه:
http://www.sobhe.ir/moratab/

**Comment by mhemrg** [comment]
این واقعا خیلی خوبه :)
