### ISSUE TITLE
 ساخت یک انتشارات در وریگول‌دات‌آی‌او

### ISSUE THREAD

**Issue by mehrad77** [pr-techblog/pr-techblog#52]
به ذهنم رسید از بجه‌ها یه نظرخواهی بکنم که نظرتون چیه اگر پول‌ریکوست رو تبدیل به یک [انتشارات](https://virgool.io/what-is-publication) در ویرگول‌دات‌آی‌او بکنیم؟

البته که یک سری امکانات ویژه رو نداره ولی حس می‌کنم می‌تونه مفید باشه. حتمن هم نیازی نیست که مطالب اینجا نباشند، شاید بشه از جفتش استفاده کرد یا حتی با بچه‌های ویرگول صحبت کرد برای امکاناتی که کد رو بهتر بشه نشون داد.

**Comment by farskid** [comment]
@mehrad77 ممنون بابت پیشنهاد. مهاجرت یا انتشارات موازی روی ویرگول چه مزایایی داره؟

**Comment by farskid** [comment]
چنتا سوال:

۱. چرا ویرگول دسترسی پذیریش بالاتره؟
۲. آیا کسی جز دوستان فنی هم تمایل دارن توی بلاگ مطلبی منتشر کنن؟

و فرض میکنیم که همه دوستان فنی با پورسه کار با گیتهاب و مفاهمیش آشنا هستن.

**Comment by mehrad77** [comment]
1. فکر می‌کنم به خاطر پیشنهادات هوشمندش در انتهای مطالب به نوشته‌های دیگر و یا مثلا امکان Instance view در تلگرام و تبلیغات خودش ویرگول در سرتاسر اینترنت. 
1. احتمالا خیر، من منظورم بیشتر سادگی نوشتن و ویرایشگر بهتر بود

**Comment by farskid** [comment]
من به شخصه با ایجاد وابستگی به یه پلتفرم دیگه موافق نیستم مگر فیچرهایی روی اون پلتفرم وجود داشته باشه اختصاصی برای استفاده از اون فیچرها مهاجرت کنیم.

به نظرم پیشنهاد مطالب مشابه و ادیتور آنلاین ایده های خیلی خوبی هستن. میشه ایشو باز کرد براشون.
از ابتدای پروژه این توی ذهنم بود که تکنولوژی پروژه رو از جکیل منتقل کنیم به
Node.js

میتونیم این حرکت رو آروم شروع کنیم.
Feel free to open issues and even better start implementing 👍

**Comment by mehrad77** [comment]
البته منظور من از مطالب مشابه، در مطالبِ بقیه بود. در واقع در کل مطالب سایت ویرگول مطالب پول‌ریکوست تبلیغ می‌شه.

**Comment by nainemom** [comment]
بحث ادیتور و سختی نوشتن مطلب توی بلاگ حل میشه بزودی.
راجع به بحث معروف‌تر بودن ویرگول و بیشتر دیده شدن مطالب اونجا، اینو میتونم بگم که ماهیت این وبلاگ بیشتر از اینکه صرفا یک وبلاگ حوزه برنامه‌نویسی باشه، توی اسمشه. اینکه برنامه‌نویس‌ها با پول‌ریکوئست بتونن توی تغییرات این وبلاگ سهیم باشن. اینجا هم می‌تونه با گذر زمان خواننده‌های بیشتری جذب کنه.

**Comment by farskid** [comment]
من دارم به دوباره نویسی پول ریکوئست با یه تکنولوژی و دیزاین بهتر فکر میکنم. بهتره این بحث رو اینجا ادامه بدیم.

https://github.com/pr-techblog/pr-techblog/issues/54
