### ISSUE TITLE
مشکل در لود صفحات

### ISSUE THREAD

**Issue by behdad222** [pr-techblog/pr-techblog#61]
تو تغییرات جدید لینک زیر صفحه سفید نشون میده
https://pullrequest.ir/%DA%AF%D9%81%D8%AA%D9%87-%D9%87%D8%A7%DB%8C-%D8%A2%D8%B1%D8%B4-%D8%AE%D8%A7%D9%86%DA%AF%D9%84%D8%AF%DB%8C-%D8%A7%D8%B2-%D8%A7%D8%B3%D9%BE%D8%A7%D8%AA%DB%8C%D9%81%D8%A7%DB%8C
و من همجا همین لینک رو شیر دادم که باعث میشه نشه دیدش

**Comment by farskid** [comment]
بهداد جان پول ریکوئست درحال انتقال به پلتفرم ویرگول هست. دامنه الان روی محتوای منتقل شده به ویرگول لود میشه.
متاسفانه ناچارا آدرس ها تغییر کردن یکم و این مطلب آدرس جدیدش اینه:
https://pullrequest.ir/%DA%AF%D9%81%D8%AA%D9%87%D9%87%D8%A7%DB%8C-%D8%A2%D8%B1%D8%B4-%D8%AE%D8%A7%D9%86%DA%AF%D9%84%D8%AF%DB%8C-%D8%A7%D8%B2-%D8%A7%D8%B3%D9%BE%D8%A7%D8%AA%DB%8C%D9%81%D8%A7%DB%8C-sravc7z452ti

داریم روی روشی کار میکنیم که آدرس های قبلی رو بتونیم به مطلب جدید ریدایرکت کنیم.
در همین راستا اگر یوزرنیم خودت در ویرگول رو بهم بدی من مطلب رو به اسم خودت میتونم منتشر کنم.

**Comment by behdad222** [comment]
فکر میکنید چقدر طول بکشه؟
اگر این روش زمان‌بر هست برم و لینک‌هارو تغییر بدم

رو ویرگول هنوز حساب ندارم

**Comment by farskid** [comment]
فکر میکنم یکی دو روزی طول بکشه چون مشکل فنی هست. به نظرم تغییر آدرس ها روش سریعتریه.

**Comment by behdad222** [comment]
بعد این لینک جدید ممکنه بعدا از کار بی‌افته؟

**Comment by farskid** [comment]
نه. این لینک جدید همیشه سرپا خواهد بود.

**Comment by behdad222** [comment]
@behdad.222
حساب من در ویرگول

**Comment by farskid** [comment]
@behdad222 مطلبتون با اکانت خودتون توی آدرس جدید منتشر شد.
https://pullrequest.ir/%DA%AF%D9%81%D8%AA%D9%87%D9%87%D8%A7%DB%8C-%D8%A2%D8%B1%D8%B4-%D8%AE%D8%A7%D9%86%DA%AF%D9%84%D8%AF%DB%8C-%D8%A7%D8%B2-%D8%A7%D8%B3%D9%BE%D8%A7%D8%AA%DB%8C%D9%81%D8%A7%DB%8C-sravc7z452ti
